import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
size = 17
offset = {x = 1, y = 4}

builtin_box_drawing = false

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
