import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Retina"}
size = 16

offset = {x = 1, y = 0}

builtin_box_drawing = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
