#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    project_rooter_outermost = false
    relativenumber = false
    enable_cursorline = false
    autocomplete_method = "neocomplcache"
    bootstrap_before = 'customfn#before'
    bootstrap_after = 'customfn#after'

# Change core config
[[layers]]
name = 'core'
enable_filetree_gitstatus = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "fzf"

[[layers]]
name = "checkers"

[[layers]]
name = 'git'
git_plugin = 'fugitive'

[[layers]]
name = 'VersionControl'

[[layers]]
name = "format"
format_on_save = true

[[layers]]
name = "treesitter"

[[layers]]
name = "colorscheme"

[[layers]]
name = "lsp"

[[layers]]
name = "lang#elixir"

[[layers]]
name = 'lang#ruby'
format_on_save = true
enabled_linters = ['rubylint', 'rubocop']

[[layers]]
name = 'lang#solidity'

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#toml"

[[layers]]
name = "test"
